"""Initial migration

Revision ID: cceb27c83422
Revises: 
Create Date: 2023-09-06 01:19:16.014262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cceb27c83422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AspNetUserRoles', schema=None) as batch_op:
        batch_op.drop_index('IX_AspNetUserRoles_RoleId')

    op.drop_table('AspNetUserRoles')
    with op.batch_alter_table('AspNetRoles', schema=None) as batch_op:
        batch_op.drop_index('RoleNameIndex')

    op.drop_table('AspNetRoles')
    op.drop_table('__EFMigrationsHistory')
    with op.batch_alter_table('AspNetRoleClaims', schema=None) as batch_op:
        batch_op.drop_index('IX_AspNetRoleClaims_RoleId')

    op.drop_table('AspNetRoleClaims')
    with op.batch_alter_table('AspNetUserLogins', schema=None) as batch_op:
        batch_op.drop_index('IX_AspNetUserLogins_UserId')

    op.drop_table('AspNetUserLogins')
    with op.batch_alter_table('AspNetUserClaims', schema=None) as batch_op:
        batch_op.drop_index('IX_AspNetUserClaims_UserId')

    op.drop_table('AspNetUserClaims')
    op.drop_table('AspNetUserTokens')
    with op.batch_alter_table('AspNetUsers', schema=None) as batch_op:
        batch_op.drop_index('EmailIndex')
        batch_op.drop_index('UserNameIndex')

    op.drop_table('AspNetUsers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AspNetUsers',
    sa.Column('Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('FirstName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('LastName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('UserName', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('NormalizedUserName', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('NormalizedEmail', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('EmailConfirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('PasswordHash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('SecurityStamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ConcurrencyStamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('PhoneNumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('PhoneNumberConfirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('TwoFactorEnabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('LockoutEnd', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('LockoutEnabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('AccessFailedCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_AspNetUsers'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('AspNetUsers', schema=None) as batch_op:
        batch_op.create_index('UserNameIndex', ['NormalizedUserName'], unique=False)
        batch_op.create_index('EmailIndex', ['NormalizedEmail'], unique=False)

    op.create_table('AspNetUserTokens',
    sa.Column('UserId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('LoginProvider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['AspNetUsers.Id'], name='FK_AspNetUserTokens_AspNetUsers_UserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'LoginProvider', 'Name', name='PK_AspNetUserTokens')
    )
    op.create_table('AspNetUserClaims',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ClaimType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ClaimValue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['AspNetUsers.Id'], name='FK_AspNetUserClaims_AspNetUsers_UserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name='PK_AspNetUserClaims')
    )
    with op.batch_alter_table('AspNetUserClaims', schema=None) as batch_op:
        batch_op.create_index('IX_AspNetUserClaims_UserId', ['UserId'], unique=False)

    op.create_table('AspNetUserLogins',
    sa.Column('LoginProvider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ProviderKey', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ProviderDisplayName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('UserId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['AspNetUsers.Id'], name='FK_AspNetUserLogins_AspNetUsers_UserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LoginProvider', 'ProviderKey', name='PK_AspNetUserLogins')
    )
    with op.batch_alter_table('AspNetUserLogins', schema=None) as batch_op:
        batch_op.create_index('IX_AspNetUserLogins_UserId', ['UserId'], unique=False)

    op.create_table('AspNetRoleClaims',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('RoleId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ClaimType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ClaimValue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['AspNetRoles.Id'], name='FK_AspNetRoleClaims_AspNetRoles_RoleId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id', name='PK_AspNetRoleClaims')
    )
    with op.batch_alter_table('AspNetRoleClaims', schema=None) as batch_op:
        batch_op.create_index('IX_AspNetRoleClaims_RoleId', ['RoleId'], unique=False)

    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    op.create_table('AspNetRoles',
    sa.Column('Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('NormalizedName', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('ConcurrencyStamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_AspNetRoles'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('AspNetRoles', schema=None) as batch_op:
        batch_op.create_index('RoleNameIndex', ['NormalizedName'], unique=False)

    op.create_table('AspNetUserRoles',
    sa.Column('UserId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('RoleId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['AspNetRoles.Id'], name='FK_AspNetUserRoles_AspNetRoles_RoleId', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['AspNetUsers.Id'], name='FK_AspNetUserRoles_AspNetUsers_UserId', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'RoleId', name='PK_AspNetUserRoles')
    )
    with op.batch_alter_table('AspNetUserRoles', schema=None) as batch_op:
        batch_op.create_index('IX_AspNetUserRoles_RoleId', ['RoleId'], unique=False)

    # ### end Alembic commands ###
